# Generated by Django 3.2.9 on 2021-12-25 09:51

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userfavouritegame',
            managers=[
                ('not_deleted_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
