# Generated by Django 3.2.9 on 2021-12-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_userfavouritegame_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userfavouritegame',
            managers=[
            ],
        ),
    ]
