# Generated by Django 3.2.9 on 2022-01-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_screenshot_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
