# Generated by Django 3.2.9 on 2021-12-25 11:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_userfavouritegame_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userfavouritegame',
            managers=[
                ('not_deleted_user_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
